добавить делегирование
Toolll1/document-flow pull request #29
Opened 2023-11-08 14:35 UTC by ya-ne-kit

Добавлено делегирование согласования: 
предыдущее согласование закрывается со статусом DELEGATED, создается новый DocProcess с recipient'ом, которому делегировали согласование

2023-11-10 17:40 UTC, FokiDoki commented
Jenkins, run CI

2023-11-10 17:40 UTC, FokiDoki commented
Can one of the admins verify this patch?

2023-11-10 17:42 UTC, FokiDoki commented
Jenkins CI/CD: Build #14: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/14/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/14/

2023-11-10 21:58 UTC, FokiDoki commented
Jenkins, run CI

2023-11-10 22:00 UTC, FokiDoki commented
Jenkins CI/CD: Build #18: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/18/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/18/

2023-11-15 16:05 UTC, FokiDoki commented
Jenkins, run CI

2023-11-15 16:06 UTC, FokiDoki commented
Jenkins CI/CD: Build `#53`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/53/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/53/

2023-11-15 16:07 UTC, vchumachenko submitted a review, later dismissed

2023-11-22 16:44 UTC, ya-ne-kit commented
Jenkins, run CI

2023-11-22 17:41 UTC, ya-ne-kit commented
Jenkins, run CI

2023-11-22 17:43 UTC, FokiDoki commented
Jenkins CI/CD: Build `#89`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/89/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/89/

2023-11-23 08:23 UTC, FokiDoki commented
Jenkins CI/CD: Build `#99`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/99/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/99/

2023-11-23 11:06 UTC, FokiDoki requested changes

2023-11-23 11:06 UTC, FokiDoki commented on src/main/java/ru/rosatom/documentflow/controllers/DocProcessController.java
> +    @PreAuthorize("@documentProcessSecurityService.isRecipient(#processUpdateRequestDto.processId, authentication.principal.id) && hasAuthority('USER')")
Нужно добавить аннотации swagger-а

2023-11-23 14:32 UTC, FokiDoki commented
Jenkins CI/CD: Build `#105`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/105/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/105/

2023-11-23 14:35 UTC, FokiDoki commented on src/main/java/ru/rosatom/documentflow/controllers/DocProcessController.java
> +    @PreAuthorize("@documentProcessSecurityService.isRecipient(#processUpdateRequestDto.processId, authentication.principal.id) && hasAuthority('USER')")
Плюс параметер recipientId передавать в  path а не в query т.к это не опциональный параметер

2023-11-23 19:27 UTC, FokiDoki commented
Jenkins CI/CD: Build `#107`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/107/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/107/

2023-11-23 19:28 UTC, ya-ne-kit commented on src/main/java/ru/rosatom/documentflow/controllers/DocProcessController.java
> +    @PreAuthorize("@documentProcessSecurityService.isRecipient(#processUpdateRequestDto.processId, authentication.principal.id) && hasAuthority('USER')")
fixed

2023-11-23 19:29 UTC, FokiDoki commented
Jenkins CI/CD: Build `#108`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/108/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/108/

2023-11-24 13:25 UTC, FokiDoki approved these changes

2023-11-24 13:26 UTC, merged