Тесты для DocumentServiceImpl
Toolll1/document-flow pull request #47
Opened 2023-11-19 14:44 UTC by SvyatoslavKlabukov

2023-11-19 14:46 UTC, FokiDoki commented
Jenkins CI/CD: Build `#64`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/64/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/64/

2023-11-19 14:47 UTC, FokiDoki commented
Jenkins CI/CD: Build `#65`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/65/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/65/

2023-11-19 15:11 UTC, FokiDoki requested changes

2023-11-19 15:11 UTC, FokiDoki commented on src/test/java/ru/rosatom/documentflow/services/impl/DocumentServiceImplTest.java
> +        List<String> pathParts = List.of("src", "main", "java", "ru", "rosatom", "documentflow", "files");
Длинный метод, слишком. Сложно читается. Создание файлов и сопутствующие проверки лучше вынести в отдельные функции

2023-11-19 15:11 UTC, FokiDoki commented on src/test/java/ru/rosatom/documentflow/services/impl/DocumentServiceImplTest.java
> +        List<String> pathParts = List.of("src", "main", "java", "ru", "rosatom", "documentflow", "files");
path стоит брать из каких-нибудь констант внутри сервиса, т.к он будет меняться часто

2023-11-19 15:11 UTC, FokiDoki commented on src/test/java/ru/rosatom/documentflow/services/impl/DocumentServiceImplTest.java
> +        assertThat("Не найден документ с id " + document.getId()).isEqualTo(exception.getMessage());
ещё бы exception на корректность проверить

2023-11-19 15:18 UTC, SvyatoslavKlabukov commented on src/test/java/ru/rosatom/documentflow/services/impl/DocumentServiceImplTest.java
> +        assertThat("Не найден документ с id " + document.getId()).isEqualTo(exception.getMessage());
Что значит "на корректность"?

2023-11-19 16:16 UTC, FokiDoki commented
Jenkins CI/CD: Build `#67`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/67/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/67/

2023-11-19 16:18 UTC, FokiDoki commented on src/test/java/ru/rosatom/documentflow/services/impl/DocumentServiceImplTest.java
> +        assertThat("Не найден документ с id " + document.getId()).isEqualTo(exception.getMessage());
Что выбрасываться конкретный exception. `ObjectNotFoundException` в нашем случае

2023-11-20 12:46 UTC, FokiDoki commented
Jenkins CI/CD: Build `#76`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/76/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/76/

2023-11-20 12:46 UTC, FokiDoki approved these changes

2023-11-20 12:46 UTC, merged