реализованы CRUD для текстового документа локально/в minio
Toolll1/document-flow pull request #48
Opened 2023-11-19 16:30 UTC by Toolll1

2023-11-19 16:32 UTC, FokiDoki commented
Jenkins CI/CD: Build `#68`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/68/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/68/

2023-11-19 17:50 UTC, FokiDoki commented
Jenkins CI/CD: Build `#74`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/74/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/74/

2023-11-19 18:32 UTC, FokiDoki commented
Jenkins CI/CD: Build `#75`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/75/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/75/

2023-11-19 18:53 UTC, FokiDoki requested changes

2023-11-19 18:53 UTC, FokiDoki commented on src/main/java/ru/rosatom/documentflow/services/impl/DocumentServiceImpl.java
> +        Document newDocument = fileService.createFile(document, null);
Можно перегрузить метод createFile, тогда не придётся передавать null
```java
Document newDocument = fileService.createFile(document);
```

2023-11-19 18:53 UTC, FokiDoki commented on src/main/java/ru/rosatom/documentflow/services/impl/DocumentServiceImpl.java
> +    public Document updateDocument(DocumentUpdateDto documentUpdateDto, Long id, Long userId) {
DTO в сервисном слое, нужно заменить на модель

2023-11-19 18:53 UTC, FokiDoki commented on src/main/java/ru/rosatom/documentflow/services/impl/DocumentServiceImpl.java
> +        Document correctDocument = fileService.updateFile(newDocument, oldDocument, null);
Тоже можно перегрузить метод чтобы null убрать

2023-11-19 18:53 UTC, FokiDoki commented on src/main/java/ru/rosatom/documentflow/services/impl/DocumentServiceImpl.java
> +        }
Дублирующаяся фунциональность. Можно вынести в отдельный метод

2023-11-19 18:53 UTC, FokiDoki commented on src/main/java/ru/rosatom/documentflow/services/impl/FileServiceLocalImpl.java
Процесс генерации файла жесткий дубликат. Я понимаю что это временная заглушка, но можно разбить это на мелкие методы и вынести одинаковый код в абстрактный класс который занимался бы генерацией файла. А особенности хранения реализовывать как раз в этих классах.

С процессом конвертации то же самое. Дубликат. Вынести в отдельный метод в родительском классе

2023-11-19 18:53 UTC, FokiDoki commented on src/main/java/ru/rosatom/documentflow/services/impl/FileServiceMinioImpl.java
> +            .credentials("admin", "Secure123$")
Креды нужно вынести в properties

2023-11-19 18:53 UTC, FokiDoki commented on src/main/java/ru/rosatom/documentflow/services/impl/FileServiceMinioImpl.java
> +                .build();
Конвертер лучше объявлять один раз на старте приложения в каком-нибудь блоке инициализации т.к на старт workerPool уходит много ресурсов. 

Path к папке с временными файлами нужно брать из properties

2023-11-19 18:53 UTC, FokiDoki commented on src/main/java/ru/rosatom/documentflow/services/impl/FileServiceMinioImpl.java
> +        document.setDocumentPath("http://127.0.0.1:9090/browser/" + bucketName);
Ссылку бы из minio как-нибудь тащить если это возможно

2023-11-20 12:42 UTC, FokiDoki approved these changes

2023-11-20 12:43 UTC, merged

2023-11-26 15:13 UTC, Toolll1 commented on src/main/java/ru/rosatom/documentflow/services/impl/DocumentServiceImpl.java
> +        }
☑

2023-11-26 15:24 UTC, Toolll1 commented on src/main/java/ru/rosatom/documentflow/services/impl/FileServiceMinioImpl.java
> +        document.setDocumentPath("http://127.0.0.1:9090/browser/" + bucketName);
так и не нашел, но спрятал))

2023-11-26 15:25 UTC, Toolll1 commented on src/main/java/ru/rosatom/documentflow/services/impl/FileServiceMinioImpl.java
> +                .build();
долго стартует WordprocessingMLPackage. его убрал в конструктор

2023-11-26 15:26 UTC, Toolll1 commented on src/main/java/ru/rosatom/documentflow/services/impl/FileServiceMinioImpl.java
> +            .credentials("admin", "Secure123$")
☑

2023-11-26 15:26 UTC, Toolll1 commented on src/main/java/ru/rosatom/documentflow/services/impl/FileServiceLocalImpl.java
☑

2023-11-26 15:27 UTC, Toolll1 commented on src/main/java/ru/rosatom/documentflow/services/impl/DocumentServiceImpl.java
> +        Document correctDocument = fileService.updateFile(newDocument, oldDocument, null);
если перегрузить, придется больше дублировать